export const BACK = 'BACK';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN';
export const CAMERA_SCREEN = 'CAMERA_SCREEN';
export const FRIENDS_SCREEN = 'FRIENDS_SCREEN';
export const DUELS_SCREEN = 'DUELS_SCREEN';
export const TOURNAMENTS_SCREEN = 'TOURNAMENTS_SCREEN';
export const LIGUES_SCREEN = 'LIGUES_SCREEN';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
